const UPLOAD_PRESET = import.meta.env.VITE_CLOUDINARY_UPLOAD_PRESET;
const UPLOAD_BASE_URL = import.meta.env.VITE_CLOUDINARY_BASE_URL;
const UPLOAD_CLOUD_NAME = import.meta.env.VITE_CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_URL = `${UPLOAD_BASE_URL}/${UPLOAD_CLOUD_NAME}/image/upload`;
export {UPLOAD_BASE_URL,UPLOAD_CLOUD_NAME,CLOUDINARY_URL,UPLOAD_PRESET}